// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXi1GU3Lqz6ThcyuPrB8-aHBpB8Uzx_Xg',
    appId: '1:382370893360:web:2db6bce3b0108a429667f5',
    messagingSenderId: '382370893360',
    projectId: 'ecommerceapp-6029a',
    authDomain: 'ecommerceapp-6029a.firebaseapp.com',
    storageBucket: 'ecommerceapp-6029a.firebasestorage.app',
    measurementId: 'G-CEKK2EZ691',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB5KtMJZoiTSnJSP1ZsSuWUrzRFBUf_q8',
    appId: '1:382370893360:android:098919e42ae4a0029667f5',
    messagingSenderId: '382370893360',
    projectId: 'ecommerceapp-6029a',
    storageBucket: 'ecommerceapp-6029a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCd7IBI9bx2NUVltiDfc4SLYMzNTF4jrc',
    appId: '1:382370893360:ios:b38328995849ab889667f5',
    messagingSenderId: '382370893360',
    projectId: 'ecommerceapp-6029a',
    storageBucket: 'ecommerceapp-6029a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );
}
